### ISSUE TITLE
Error reported for clion 1.0.3

### ISSUE THREAD

**Issue by Synthetisoft** [rover12421/JetbrainsPatchKeygen#15]
Exception in thread "main" java.io.IOException: ?e? ep?t??peta? ? p??sßas? at java.io.WinNTFileSystem.createFileExclusively(Native Method) at java.io.File.createTempFile(Unknown Source) at com.rover12421.crack.jerbrains.ClionPatch.patch(ClionPatch.java:38) at com.rover12421.crack.jerbrains.Main.main(Main.java:106

**Comment by Synthetisoft** [comment]
That error was because the person didn't run as Admin but the patch still didn't work for 1.0.3.

**Comment by rover12421** [comment]
please check your run permissions.
if your os is win7+, and `clion` install drive `C`, try `run administrator`.

**Comment by sztosz** [comment]
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at com.rover12421.crack.jerbrains.ClionPatch.patch(ClionPatch.java:84)
	at com.rover12421.crack.jerbrains.Main.main(Main.java:106)
	Suppressed: java.util.zip.ZipException: invalid entry size (expected 108 but got 0 bytes)
		at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:288)
		at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:361)
		at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
		at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:378)
		at com.rover12421.crack.jerbrains.ClionPatch.patch(ClionPatch.java:91)
		... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

**Comment by Synthetisoft** [comment]
Running as administrator removes the error. The patch works good but it does not work for CLion 1.0.3. I was wondering if you could take a look at that. 1.0.3 was recently released.

Thanks

**Comment by sztosz** [comment]
It does not matter, if i run it as local account or sudo, or copy jar somewhere else ie. /tmp. I'm on linux

**Comment by Synthetisoft** [comment]
Make a new issue for it. This thread is for CLion 1.0.3 support. I initially thought the error was related but that was a mistake.

**Comment by sztosz** [comment]
I tried on windows with clion 1.0.3, and i had no trouble there. Clion.jar was patched successfully, generated key was taken by clion without complain and clion got registered. If you need it on linux, then easiest way is copy patched clion.jar from windows to linux, it works without any problem there. So i don't  think there is any issue with 1.0.3. "My" error comes, i think, from using java 8 instead of 7 on my linux machine.

**Comment by Synthetisoft** [comment]
1.0.4 is out now. about to try. As I've been working more and more with Java and stumbled upon this I'm more interested in how this code works than anything else.

**Comment by SalahAdDin** [comment]
It's the same un Linux?
